routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\FrontEnd\FrontendController;
use App\Http\Controllers\HomeWork\ColorController;
use App\Http\Controllers\HomeWork\CountryController;
use App\Http\Controllers\HomeWork\TagController;
use App\Http\Controllers\Private\BrandController;
use App\Http\Controllers\Private\CategoryController;
use App\Http\Controllers\Private\ProductController;
use App\Http\Controllers\Private\SupplierController;
use App\Http\Controllers\Private\UnitController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Route::get('/register', [DashboardController::class, 'registration']);
Route::get('/login', [DashboardController::class, 'login']);
Route::post('/register', [AuthController::class, 'register'])->name('auth.register');
Route::post('/login', [AuthController::class, 'login']);

Route::get('/403', [ErrorController::class, 'forbidden'])->name('error.403');

Route::middleware('admin')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');
    Route::prefix('admin')->group(function () {
        Route::get('/', [DashboardController::class, 'index']);

        // Product
        Route::get('/products', [ProductController::class, 'index']);
        Route::get('/product/create', [ProductController::class, 'create']);
        Route::post('/product/store', [ProductController::class, 'store']);

        // Supplier
        Route::get('/suppliers', [SupplierController::class, 'index']);
        Route::get('/supplier/create', [SupplierController::class, 'create']);
        Route::post('/supplier/store', [SupplierController::class, 'store']);
        Route::get('/supplier/edit', [SupplierController::class, 'edit']);
        Route::get('/supplier/delete', [SupplierController::class, 'delete']);

        // Category
        Route::get('/categories', [CategoryController::class, 'index']);
        Route::get('/category/create', [CategoryController::class, 'create']);
        Route::post('/category/store', [CategoryController::class, 'store']);
        Route::get('/category/edit', [CategoryController::class, 'edit']);
        Route::get('/category/delete', [CategoryController::class, 'delete']);

        // Brand
        Route::get('/brands', [BrandController::class, 'index']);
        Route::get('/brand/create', [BrandController::class, 'create']);
        Route::post('/brand/store', [BrandController::class, 'store']);
        Route::get('/brand/edit', [BrandController::class, 'edit']);
        Route::get('/brand/delete', [BrandController::class, 'delete']);

        // Brand
        Route::get('/units', [UnitController::class, 'index']);
        Route::get('/unit/create', [UnitController::class, 'create']);
        Route::post('/unit/store', [UnitController::class, 'store']);
        Route::get('/unit/edit', [UnitController::class, 'edit']);
        Route::get('/unit/delete', [UnitController::class, 'delete']);
    });
});




Route::prefix('frontend')->group(function () {
    Route::get('/', [FrontendController::class, 'index']);
    Route::get('/product-list', [FrontendController::class, 'productList']);
    Route::get('/product-details', [FrontendController::class, 'productDetails']);
    Route::get('/cart', [FrontendController::class, 'productCart']);
    Route::get('/checkout', [FrontendController::class, 'checkout']);
    Route::get('/order', [FrontendController::class, 'order']);
});

Route::prefix('homework')->group(function () {
    Route::get('/', [DashboardController::class, 'index']);
    Route::resource('colors', ColorController::class);
    Route::resource('countries', CountryController::class);
    Route::resource('tags', TagController::class);
    Route::get('/tag/download/pdf', [TagController::class, 'downloadPdf'])->name('tags.pdf');

    Route::resource('courses', CourseController::class);
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Color extends Model
{

    use HasFactory, SoftDeletes;
    protected $table = 'colors';

    protected $fillable = ['title', 'color_code'];

    // protected $rules = [
    //     'email' => 'sometimes|required|email|unique:users',

    // ];
}

app/Http/Controllers/HomeWork/ColorController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Color;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $colors = Color::orderBy('id', 'desc')->paginate(10);
            return view('homeWork.color.index', compact('colors'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.color.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request->validate([
        //     'name' => 'required|unique:users'
        // ]);
        try {
            Color::create([
                'title' => $request->input('title'),
                'color_code' => $request->input('color')
            ]);
            Alert::success('Great Job!', 'Color Create Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $color = Color::find($id);
        return view('homeWork.color.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $color = Color::find($id);
            $color->update([
                'title' => $request->input('title'),
                'color_code' => $request->input('color'),
            ]);
            Alert::success('Great Job!', 'Color Update Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $color = Color::find($id);
            $color->delete();
            Alert::info('Great Job!', 'Color Delete Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }
}

app/Http/Controllers/HomeWork/CountryController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Country;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::orderBy('id', 'desc')->get();
        return view('homeWork.country.index', compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.country.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $id = $request->input('id');

            if ($id > 0) {
                $country = Country::find($id);
            } else {
                $country = new Country();
            }

            $country->title = $request->input('name');
            $country->save();
            Alert::success('Great Job!', 'Country Create Successfully!');
            return redirect()->route('countries.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $country = Country::find($id);
            return view('homeWork.country.edit', compact('country'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $country = Country::find($id);
            $country->title = $request->input('name');
            $country->save();

            Alert::success('Great Job!', 'Country Update Successfully!');
            return redirect()->route('countries.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeWork/TagController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use PDF;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderBy('id', 'desc')->get();
        return view('homeWork.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $id = $request->input('id');

            if ($id > 0) {
                $tag = Tag::find($id);
            } else {
                $tag = new Tag();
            }

            $tag->title = $request->input('title');
            $tag->save();
            Alert::success('Great Job!', 'Tag Create Successfully!');
            return redirect()->route('tags.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function downloadPdf()
    {
        $tags = Tag::all();
        $pdf = PDF::loadView('homeWork.tag.pdf', compact('tags'));
        return $pdf->download('tags.pdf');
    }
}

resources/views/homeWork/color/create.blade.php
<x-admin.layout.master>
    <x-slot:title>Color </x-slot:title>
    <x-slot:pageTitle>Create Color </x-slot:pageTitle>
    <div class="card p-4">
        <div class="card-header">
           
            <a href="{{ route('colors.index') }}" class="btn btn-info">Color List</a>
        </div>
        <form action="{{ route('colors.store') }}" method="POST" >
            @csrf
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="title" placeholder="Enter your color name" label="Name:" labelFor="title"  id="title" type="text" value="{{ old('title') }}" /> 
                        <x-admin.utilities.form.error name="title" />
                    </div>
                    
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="color" placeholder="Pic your color" label="Pick Color:" labelFor="color" class="form-control-color"  id="color" type="color" value="{{ old('color') }}" /> 
                        {{-- <x-admin.utilities.form.error name="name" /> --}}
                    </div>

                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
      
        </form>
    </div>

</x-admin.layout.master>

resources/views/homeWork/color/edit.blade.php
<x-admin.layout.master>
    <x-slot:title>Color </x-slot:title>
    <x-slot:pageTitle>Update Color </x-slot:pageTitle>
    <div class="card p-4">
        <div class="card-header">
           
            <a href="{{ route('colors.index') }}" class="btn btn-info">Color List</a>
        </div>
        <form action="{{ route('colors.update', ['color' => $color->id]) }}" method="POST" >
            @csrf
            @method('patch')
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="title" placeholder="Enter your color name" label="Name:" labelFor="title"  id="title" type="text" value="{{ old('title', $color->title) }}" /> 
                        <x-admin.utilities.form.error name="title" />
                    </div>
                    
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="color" placeholder="Pic your color" label="Pick Color:" labelFor="color" class="form-control-color"  id="color" type="color" value="{{ old('color', $color->color_code) }}" /> 
                        {{-- <x-admin.utilities.form.error name="name" /> --}}
                    </div>

                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
           
           
            
        </form>
    </div>

</x-admin.layout.master>

resources/views/homeWork/color/index.blade.php
<x-admin.layout.master>
    @push('css')
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.2/dist/sweetalert2.min.css"> 
    @endpush
    <x-slot:title>Color List</x-slot:title>
    <x-slot:pageTitle>Color List </x-slot:pAddressTitle>
   
    
    <div class="card mb-4">
        <div class="card-header">
           
            <a href="{{ route('colors.create')}}" class="btn btn-info">Add New</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Name</th>
                        <th>Color Code</th>
                        <th>Color</th>
                        <th style="width: 20%">Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>SL</th>
                        <th>Name</th>
                        <th>Color Code</th>
                        <th>Color</th>
                        <th style="width: 20%">Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($colors as $key=>$item)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->color_code}}</td>
                        <td>
                            <div style="width:100%; height:30px; background-color: {{$item->color_code }}"></div>
                        </td>
                        <td>
                            <a href="{{ route('colors.edit', ['color' => $item->id]) }}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="" class="btn btn-info btn-sm">View</a>

                            <form action="{{ route('colors.destroy', ['color' => $item->id]) }}" method="POST" style="display: inline">
                                @csrf
                                @method('delete')
                                <button onclick="confirm('Are you sure want to delete?')" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                           
                        </td>
                    </tr>
                    @endforeach
                    
                  
                </tbody>
            </table>
            {{ $colors->links() }}
        </div>
    </div>

    
    
</x-admin.layout.master>