routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\FrontEnd\FrontendController;
use App\Http\Controllers\HomeWork\ColorController;
use App\Http\Controllers\HomeWork\CountryController;
use App\Http\Controllers\HomeWork\TagController;
use App\Http\Controllers\Private\BrandController;
use App\Http\Controllers\Private\CategoryController;
use App\Http\Controllers\Private\ProductController;
use App\Http\Controllers\Private\SupplierController;
use App\Http\Controllers\Private\UnitController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Route::get('/register', [DashboardController::class, 'registration']);
Route::get('/login', [DashboardController::class, 'login']);
Route::post('/register', [AuthController::class, 'register'])->name('auth.register');
Route::post('/login', [AuthController::class, 'login']);

Route::get('/403', [ErrorController::class, 'forbidden'])->name('error.403');

Route::middleware('admin')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');
    Route::prefix('admin')->group(function () {
        Route::get('/', [DashboardController::class, 'index']);

        // Product
        Route::get('/products', [ProductController::class, 'index']);
        Route::get('/product/create', [ProductController::class, 'create']);
        Route::post('/product/store', [ProductController::class, 'store']);

        // Supplier
        Route::get('/suppliers', [SupplierController::class, 'index']);
        Route::get('/supplier/create', [SupplierController::class, 'create']);
        Route::post('/supplier/store', [SupplierController::class, 'store']);
        Route::get('/supplier/edit', [SupplierController::class, 'edit']);
        Route::get('/supplier/delete', [SupplierController::class, 'delete']);

        // Category
        Route::get('/categories', [CategoryController::class, 'index']);
        Route::get('/category/create', [CategoryController::class, 'create']);
        Route::post('/category/store', [CategoryController::class, 'store']);
        Route::get('/category/edit', [CategoryController::class, 'edit']);
        Route::get('/category/delete', [CategoryController::class, 'delete']);

        // Brand
        Route::get('/brands', [BrandController::class, 'index']);
        Route::get('/brand/create', [BrandController::class, 'create']);
        Route::post('/brand/store', [BrandController::class, 'store']);
        Route::get('/brand/edit', [BrandController::class, 'edit']);
        Route::get('/brand/delete', [BrandController::class, 'delete']);

        // Brand
        Route::get('/units', [UnitController::class, 'index']);
        Route::get('/unit/create', [UnitController::class, 'create']);
        Route::post('/unit/store', [UnitController::class, 'store']);
        Route::get('/unit/edit', [UnitController::class, 'edit']);
        Route::get('/unit/delete', [UnitController::class, 'delete']);
    });
});




Route::prefix('frontend')->group(function () {
    Route::get('/', [FrontendController::class, 'index']);
    Route::get('/product-list', [FrontendController::class, 'productList']);
    Route::get('/product-details', [FrontendController::class, 'productDetails']);
    Route::get('/cart', [FrontendController::class, 'productCart']);
    Route::get('/checkout', [FrontendController::class, 'checkout']);
    Route::get('/order', [FrontendController::class, 'order']);
});

Route::prefix('homework')->group(function () {
    Route::get('/', [DashboardController::class, 'index']);
    Route::resource('colors', ColorController::class);
    Route::resource('countries', CountryController::class);
    Route::resource('tags', TagController::class);
    Route::get('/tag/download/pdf', [TagController::class, 'downloadPdf'])->name('tags.pdf');

    Route::resource('courses', CourseController::class);
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Course extends Model
{
    use HasFactory, SoftDeletes;
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use Exception;
use Helper;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::orderBy('id', 'desc')->latest()->paginate(10);
        // return $courses;
        return view('homeWork.course.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.course.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'title' => 'required',
                'start_date' => 'required',
                'instructor_name' => 'required',
            ]);
            $course = new Course();
            $course->title = $request->input('title');
            $course->batch_no = $request->input('batch_no');
            $course->start_date = $request->input('start_date');
            $course->end_date = $request->input('end_date');
            $course->instructor_name = $request->input('instructor_name');
            $course->banner_uri = Helper::uploadImage($request->file('image'), 'courses');
            $course->is_active = $request->input('is_active') ? true : false;
            $course->course_type = $request->input('course_type');
            $course->save();
            Alert::success('Great Job!', 'Course Create Successfully!');
            return redirect()->route('courses.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $course = Course::find($id);
            return view('homeWork.course.show', compact('course'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $course = Course::find($id);

            return view('homeWork.course.edit', compact('course'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $course = Course::find($id);
            $course->title = $request->input('title');
            $course->batch_no = $request->input('batch_no');
            $course->start_date = $request->input('start_date');
            $course->end_date = $request->input('end_date');
            $course->instructor_name = $request->input('instructor_name');
            $course->banner_uri = Helper::uploadImage($request->file('image'), 'courses') ?? $course->banner_uri;
            $course->is_active = $request->input('is_active') ? true : false;
            $course->course_type = $request->input('course_type');
            $course->save();
            Alert::success('Great Job!', 'Course Update Successfully!');
            return redirect()->route('courses.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $course = Course::find($id);
            $course->delete();
            Alert::success('Great Job!', 'Course Delete Successfully!');
            return redirect()->route('courses.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }
}

app/Http/Controllers/HomeWork/ColorController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Color;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $colors = Color::orderBy('id', 'desc')->paginate(10);
            return view('homeWork.color.index', compact('colors'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.color.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request->validate([
        //     'name' => 'required|unique:users'
        // ]);
        try {
            Color::create([
                'title' => $request->input('title'),
                'color_code' => $request->input('color')
            ]);
            Alert::success('Great Job!', 'Color Create Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $color = Color::find($id);
        return view('homeWork.color.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $color = Color::find($id);
            $color->update([
                'title' => $request->input('title'),
                'color_code' => $request->input('color'),
            ]);
            Alert::success('Great Job!', 'Color Update Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $color = Color::find($id);
            $color->delete();
            Alert::info('Great Job!', 'Color Delete Successfully!');
            return redirect()->route('colors.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }
}

app/Http/Controllers/HomeWork/CountryController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Country;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::orderBy('id', 'desc')->get();
        return view('homeWork.country.index', compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.country.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $id = $request->input('id');

            if ($id > 0) {
                $country = Country::find($id);
            } else {
                $country = new Country();
            }

            $country->title = $request->input('name');
            $country->save();
            Alert::success('Great Job!', 'Country Create Successfully!');
            return redirect()->route('countries.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $country = Country::find($id);
            return view('homeWork.country.edit', compact('country'));
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $country = Country::find($id);
            $country->title = $request->input('name');
            $country->save();

            Alert::success('Great Job!', 'Country Update Successfully!');
            return redirect()->route('countries.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeWork/TagController.php
<?php

namespace App\Http\Controllers\HomeWork;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Exception;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use PDF;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderBy('id', 'desc')->get();
        return view('homeWork.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('homeWork.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $id = $request->input('id');

            if ($id > 0) {
                $tag = Tag::find($id);
            } else {
                $tag = new Tag();
            }

            $tag->title = $request->input('title');
            $tag->save();
            Alert::success('Great Job!', 'Tag Create Successfully!');
            return redirect()->route('tags.index');
        } catch (Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function downloadPdf()
    {
        $tags = Tag::all();
        $pdf = PDF::loadView('homeWork.tag.pdf', compact('tags'));
        return $pdf->download('tags.pdf');
    }
}

resources/views/homeWork/course/create.blade.php
<x-admin.layout.master>
    <x-slot:title>Course </x-slot:title>
    <x-slot:pageTitle>Create Course </x-slot:pageTitle>
    <div class="card p-4">
        <div class="card-header">
           
            <a href="{{ route('courses.index') }}" class="btn btn-info">Course List</a>
        </div>
        <form action="{{ route('courses.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="title" placeholder="Enter course name" label="Title:" labelFor="title"  id="title" type="text" value="{{ old('title') }}" /> 
                        <x-admin.utilities.form.error name="title" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="batch_no" placeholder="Example: Pondit-5" label="Batch No:" labelFor="batch_no"  id="batch_no" type="text" value="{{ old('batch_no') }}" /> 
                        <x-admin.utilities.form.error name="batch_no" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="start_date" placeholder="Example: Pondit-5" label="Start Date:" labelFor="start_date"  id="start_date" type="date" value="{{ old('start_date') }}" /> 
                        <x-admin.utilities.form.error name="start_date" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="end_date" placeholder="Example: Pondit-5" label="End Date:" labelFor="end_date"  id="end_date" type="date" value="{{ old('end_date') }}" /> 
                        <x-admin.utilities.form.error name="end_date" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="instructor_name" placeholder="Enter course name" label="Instructor Name:" labelFor="instructor_name"  id="instructor_name" type="text" value="{{ old('instructor_name') }}" /> 
                        <x-admin.utilities.form.error name="instructor_name" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="image" placeholder="Upload your image" label="Image:" labelFor="iamge"  id="image" type="file" value="{{ old('image') }}" /> 
                        {{-- <x-admin.utilities.form.error name="name" /> --}}
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3 mt-3">
                            <input type="checkbox"  id="is_active" placeholder="Enter address" value="1" name="is_active">
                            <label for="is_active" class="form-label">Is Active:</label>
                          </div>
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.select name="course_type"  label="Course Type:" labelFor="course_type"  id="course_type"  /> 
                        <x-admin.utilities.form.error name="course_type" />
                    </div>
                    
                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
           
           
            
        </form>
    </div>

</x-admin.layout.master>

resources/views/homeWork/course/edit.blade.php
<x-admin.layout.master>
    <x-slot:title>Course </x-slot:title>
    <x-slot:pageTitle>Update </x-slot:pageTitle>
    <div class="card p-4">
        <div class="card-header"> 
            <a href="{{ route('courses.index')}}" class="btn btn-info">Course List</a>
        </div>
        <form action="{{ route('courses.update', ['course' => $course->id])}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('patch')
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="title" placeholder="Enter course name" label="Title:" labelFor="title"  id="title" type="text" value="{{ old('title', $course->title) }}" /> 
                        <x-admin.utilities.form.error name="title" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="batch_no" placeholder="Example: Pondit-5" label="Batch No:" labelFor="batch_no"  id="batch_no" type="text" value="{{ old('batch_no', $course->batch_no) }}" /> 
                        <x-admin.utilities.form.error name="batch_no" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="start_date" placeholder="Example: Pondit-5" label="Start Date:" labelFor="start_date"  id="start_date" type="date" value="{{ old('start_date', $course->start_date) }}" /> 
                        <x-admin.utilities.form.error name="start_date" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="end_date" placeholder="Example: Pondit-5" label="End Date:" labelFor="end_date"  id="end_date" type="date" value="{{ old('end_date', $course->end_date) }}" /> 
                        <x-admin.utilities.form.error name="end_date" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="instructor_name" placeholder="Enter course name" label="Instructor Name:" labelFor="instructor_name"  id="instructor_name" type="text" value="{{ old('instructor_name', $course->instructor_name) }}" /> 
                        <x-admin.utilities.form.error name="instructor_name" />
                    </div>
                    <div class="col-md-6">
                        <img src="{{ asset('storage/courses') .'/' . @$course->banner_uri ?? "default.jpg"}}" alt="{{ $course->name}}" width="30" />
                        <x-admin.utilities.form.input name="image" placeholder="Upload your image" label="Image:" labelFor="iamge"  id="image" type="file" value="{{ old('image') }}" /> 
                        {{-- <x-admin.utilities.form.error name="name" /> --}}
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3 mt-3">
                            <input type="checkbox"  id="is_active" {{ $course->is_active ? 'checked' : ''}} placeholder="Enter address" value="1" name="is_active">
                            <label for="is_active" class="form-label">Is Active:</label>
                          </div>
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.select name="course_type" data="{{ $course->course_type }}"  label="Course Type:" labelFor="course_type"  id="course_type"  /> 
                        <x-admin.utilities.form.error name="course_type" />
                    </div>
                    
                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            
        </form>
    </div>

</x-admin.layout.master>

resources/views/homeWork/course/index.blade.php
<x-admin.layout.master>
    @push('css')
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.2/dist/sweetalert2.min.css"> 
    @endpush
    <x-slot:title>Course </x-slot:title>
    <x-slot:pageTitle>Course List </x-slot:pAddressTitle>
   
    
    <div class="card mb-4">
        <div class="card-header">
           
            <a href="{{ route('courses.create') }}" class="btn btn-info">Add New</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Instructor Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Status</th>
                        <th style="width:180px; ">Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>SL</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Instructor Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Status</th>
                        <th style="width:120px; ">Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($courses as $key=>$item)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td><img src="{{ asset('storage/courses') .'/' . @$item->banner_uri ?? "default.jpg"}}" alt="{{ $item->name}}" width="30" /></td>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->instructor_name }}</td>
                        <td>{{ $item->start_date }}</td>
                        <td>{{ $item->end_date }}</td>
                        <td><span class="badge {{ $item->is_active ? 'bg-primary' : 'bg-secondary'}}">{{ $item->is_active ? 'Active' : 'In Active'}}</span></td>
                       
                        <td>
                            <a href="{{ route('courses.edit', ['course' => $item->id])}}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="{{ route('courses.show', ['course' => $item->id]) }}" class="btn btn-info btn-sm">View</a>
                            <form action="{{ route('courses.destroy', ['course' => $item->id]) }}" method="POST" style="display: inline">
                                @csrf
                                @method('delete')
                                <button onclick="return confirm('Are you sure want to delete?')" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    
                   
                </tbody>
            </table>
            {{ $courses->links()}}
        </div>
    </div>

    
    
</x-admin.layout.master>

resources/views/homeWork/course/show.blade.php
<x-admin.layout.master>
    @push('css')
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.2/dist/sweetalert2.min.css"> 
    @endpush
    <x-slot:title>Course Show</x-slot:title>
    <x-slot:pageTitle>Course Show </x-slot:pAddressTitle>
   
    
    <div class="card mb-4">
        <div class="card-header">
           
            <a href="{{ route('courses.index') }}" class="btn btn-info">Course List</a>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>Title:</th>
                    <td>{{ $course->title}}</td>
                    <th>Mentor Name</th>
                    <td>{{ $course->instructor_name}}</td>
                    <th>Batch</th>
                    <td>{{ $course->batch_no}}</td>
                </tr>
                <tr>
                    <th>
                        Start Date
                    </th>
                    <td>{{ $course->start_date}}</td>
                    <th>
                        End Date
                    </th>
                    <td>{{ $course->end_date}}</td>
                    <th>
                        Status
                    </th>
                    <td>{{ $course->is_active ? 'Active' : 'In Active'}}</td>
                </tr>
                <tr>
                    <th>Course Type</th>
                    <td>{{ $course->course_type }}</td>
                    <th>Banner</th>
                    <td>
                        <img src="{{ asset('storage/courses') .'/' . @$course->banner_uri ?? "default.jpg"}}" alt="{{ $course->name}}" width="50" />
                    </td>
                </tr>
            </table>
        </div>
    </div>

    
    
</x-admin.layout.master>